name: Build & Deploy on GitHub Pages
on:
  push:
    branches:
      - "main"
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          version: 20.x
      - name: Checkout git
        uses: actions/checkout@v2
      - name: Clean install packages
        run: npm ci
      - name: Build Vue app
        run: |
          git checkout --orphan gh-pages
          npm run build
          git --work-tree dist add --all
          git --work-tree dist commit -m 'Deploy'
          git config user.name "Raidzin" && git config user.email "60663550+Raidzin@users.noreply.github.com"
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f main
          git branch -D gh-pages